"""B 站弹幕 XML 的解析与导出。"""

import logging
import xml.etree.ElementTree as ET
from pathlib import Path
from xml.dom import minidom

from danmaku_sender.types.models.common import UnsentDanmakusRecord, VideoTarget
from danmaku_sender.types.models.danmaku import Danmaku
from danmaku_sender.types.models.queue import QueueTask, TaskConfig

logger = logging.getLogger(__name__)


class DanmakuXml:
    """B 站弹幕 XML 文档的读写。"""

    @staticmethod
    def parse_file(xml_path: Path) -> list[Danmaku]:
        """读取本地 XML 文件并解析其中的弹幕。

        Args:
            xml_path: XML 文件路径。

        Returns:
            list[Danmaku]: 解析出的弹幕列表；文件中没有弹幕时为空列表。

        Raises:
            FileNotFoundError: 文件不存在。
            ValueError: XML 结构无法解析。
        """
        try:
            with open(xml_path, 'r', encoding='utf-8') as f:
                xml = f.read()
            logger.debug(f"已成功加载 XML 文件: {xml_path}")
            return DanmakuXml._parse_string(xml)

        except FileNotFoundError:
            logger.error(f"弹幕文件不存在: {xml_path}")
            raise

        except Exception as e:
            logger.error(f"文件读取失败: {xml_path}, error: {e}", exc_info=True)
            raise

    @staticmethod
    def parse_online_dmids(xml: str) -> list[str]:
        """从在线弹幕 XML 中提取服务器身份 dmid。

        Args:
            xml: 完整的弹幕 XML 文档。

        Returns:
            list[str]: 出现顺序与文档一致的 dmid 列表；没有身份字段的条目不计入。
        """
        if not xml or not xml.strip():
            return []

        dmids: list[str] = []
        for node in DanmakuXml._iter_nodes(xml):
            p_attr = node.get('p', '').split(',')
            if dmid := Danmaku.dmid_from_xml(p_attr):
                dmids.append(dmid)
        return dmids

    @staticmethod
    def load_task(xml_path: Path, config: TaskConfig) -> QueueTask | None:
        """读取本地 XML 文件并组装成一条未指定视频目标的任务草稿。

        解析失败或文件中没有弹幕时返回 None。任务状态为 UNCONFIGURED。

        Args:
            xml_path: XML 文件路径。
            config: 入队时定死的发送节奏快照。

        Returns:
            QueueTask | None: 任务草稿；文件不可用时为 None。
        """
        try:
            danmakus = DanmakuXml.parse_file(xml_path)
        except Exception as e:
            logger.error(f"弹幕文件解析失败: {xml_path} — {e}")
            return None

        if not danmakus:
            logger.warning(f"弹幕文件为空: {xml_path}")
            return None

        task = QueueTask(
            target=VideoTarget.unset(),
            danmakus=danmakus,
            config_snapshot=config,
            xml_path=xml_path,
        )
        task.status = task.initial_status
        return task

    @staticmethod
    def export_unsent(records: list[UnsentDanmakusRecord], filepath: Path) -> None:
        """将未发送弹幕按失败原因分组写出为 XML 文件。

        Args:
            records: 未发送弹幕记录，每条含 `dm` 与失败 `reason`。
            filepath: 输出文件路径。

        Raises:
            OSError: 文件写入失败。
        """
        root = DanmakuXml._new_root(comment=' Generated by BiliDanmakuSender ')

        grouped_data: dict[str, list[Danmaku]] = {}
        for item in records:
            reason = str(item.get('reason', '未归类'))
            grouped_data.setdefault(reason, []).append(item['dm'])

        for reason, dms in grouped_data.items():
            safe_reason = reason.replace('--', ' - ').strip('-')
            root.append(ET.Comment(f' === 失败原因: {safe_reason} (共 {len(dms)} 条) === '))
            DanmakuXml._append_danmakus(root, sorted(dms, key=lambda x: x.progress))

        DanmakuXml._write_xml(
            root, filepath, f"成功将 {len(records)} 条弹幕及原因分类保存到 '{filepath}'。"
        )

    @staticmethod
    def export_danmakus(danmakus: list[Danmaku], filepath: Path) -> None:
        """将弹幕写出为 XML 文件。

        Args:
            danmakus: 要导出的弹幕列表。
            filepath: 输出文件路径。

        Raises:
            OSError: 文件写入失败。
        """
        root = DanmakuXml._new_root(comment=' Generated by BiliDanmakuSender Editor ')
        DanmakuXml._append_danmakus(root, sorted(danmakus, key=lambda x: x.progress))
        DanmakuXml._write_xml(
            root, filepath, f"成功将 {len(danmakus)} 条弹幕导出到 '{filepath}'。"
        )

    @staticmethod
    def _parse_string(xml: str) -> list[Danmaku]:
        """解析完整的弹幕 XML 文档。

        Args:
            xml: 完整的弹幕 XML 文档。

        Returns:
            list[Danmaku]: 解析出的弹幕列表。
        """
        if not xml or not xml.strip():
            logger.warning("接收到的 XML 内容为空")
            return []

        results = []
        for node in DanmakuXml._iter_nodes(xml):
            if dm := DanmakuXml._parse_node(node):
                results.append(dm)

        return results

    @staticmethod
    def _iter_nodes(xml: str):
        """解析 XML 并产出 <d> 节点"""
        try:
            root = ET.fromstring(xml)
        except ET.ParseError as e:
            logger.error(f"XML 结构解析失败: {e}")
            raise ValueError(f"XML 结构解析失败: {e}") from e
        return root.findall('d')

    @staticmethod
    def _parse_node(node: ET.Element) -> Danmaku | None:
        """解析单个 <d> 节点"""
        text = node.text
        p_attr = node.get('p', '').split(',')

        # 过滤空弹幕
        if not text or not text.strip():
            return

        # 检查属性完整性
        if len(p_attr) < 1:
            logger.warning(f"弹幕属性丢失，跳过此条: {p_attr}")
            return

        try:
            return Danmaku.from_xml(p_attr, text.strip())
        except Exception as e:
            logger.warning(
                "单条弹幕解析失败: %s | text=%r, p_attr=%r",
                e, text.strip(), node.get('p', ',')
            )
            return

    @staticmethod
    def _new_root(comment: str) -> ET.Element:
        root = ET.Element('i')
        root.append(ET.Comment(comment))
        return root

    @staticmethod
    def _append_danmakus(root: ET.Element, danmakus: list[Danmaku]) -> None:
        for dm in danmakus:
            p_attr = f"{dm.progress/1000},{dm.mode},{dm.fontsize},{dm.color},0,0,0,0,0"
            d_tag = ET.SubElement(root, 'd', {'p': p_attr})
            d_tag.text = dm.msg

    @staticmethod
    def _write_xml(root: ET.Element, filepath: Path, success_msg: str) -> None:
        """将 XML 树格式化并写入文件"""
        rough_string = ET.tostring(root, 'utf-8')
        reparsed_document = minidom.parseString(rough_string)
        pretty_xml = reparsed_document.toprettyxml(indent="  ", encoding="utf-8")
        try:
            with open(filepath, 'wb') as f:
                f.write(pretty_xml)
            logger.info(f"✅ {success_msg}")
        except Exception as e:
            logger.error(f"❌ 保存弹幕 XML 失败: {e}", exc_info=True)
            raise
