import logging
import xml.etree.ElementTree as ET
from xml.dom import minidom
from typing import TypedDict

from ..models.danmaku import Danmaku


logger = logging.getLogger("DanmakuExporter")


class UnsentDanmakusRecord(TypedDict):
    dm: Danmaku
    reason: str


def create_xml_from_danmakus(danmakus: list[UnsentDanmakusRecord], filepath: str) -> None:
    """
    将弹幕字典列表转换为B站XML格式并保存到文件。
    期望输入: [{'dm': dict, 'reason': str}, ...]
    """
    root = ET.Element('i')
    root.append(ET.Comment(' Generated by BiliDanmakuSender '))

    grouped_data: dict[str, list[Danmaku]] = {}
    for item in danmakus:
        reason = str(item.get('reason', '未归类'))
        if reason not in grouped_data:
            grouped_data[reason] = []
        grouped_data[reason].append(item['dm'])

    # 写入 XML
    for reason, dms in grouped_data.items():
        safe_reason = reason.replace('--', ' - ').strip('-')
        root.append(ET.Comment(f' === 失败原因: {safe_reason} (共 {len(dms)} 条) === '))
        
        # 组内按视频时间排序，方便用户后续查看/修改
        dms.sort(key=lambda x: x.progress)
        
        for dm in dms:
            p_attr = f"{dm.progress/1000},{dm.mode},{dm.fontsize},{dm.color},0,0,0,0,0"
            d_tag = ET.SubElement(root, 'd', {'p': p_attr})
            d_tag.text = dm.msg

    # 格式化并保存
    rough_string = ET.tostring(root, 'utf-8')
    reparsed_document = minidom.parseString(rough_string)
    pretty_xml = reparsed_document.toprettyxml(indent="  ", encoding="utf-8")
    try:
        with open(filepath, 'wb') as f:
            f.write(pretty_xml)
        logger.info(f"✅ 成功将 {len(danmakus)} 条弹幕及原因分类保存到 '{filepath}'。")
    except Exception as e:
        logger.error(f"❌ 保存未发送弹幕到XML文件失败: {e}", exc_info=True)